"""phase 15 D-9 BD local features

Revision ID: 03e2fa43574f
Revises: 5d65a11a53a3
Create Date: 2026-05-24 03:33:35.724507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e2fa43574f'
down_revision = '5d65a11a53a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_etas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('district_etas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_etas_district'), ['district'], unique=True)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'prayer_time_delivery', sa.Boolean(),
            nullable=False, server_default=sa.false(),
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('prayer_time_delivery')

    with op.batch_alter_table('district_etas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_etas_district'))

    op.drop_table('district_etas')
    # ### end Alembic commands ###
