"""phase 1: vendor verification (KYC) fields

Revision ID: 0500a8293dff
Revises: 1bdd30abfad0
Create Date: 2026-05-22 14:54:30.769299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0500a8293dff'
down_revision = '1bdd30abfad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('trade_license_no', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('trade_license_doc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nid_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nid_doc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_submitted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.drop_column('verification_submitted_at')
        batch_op.drop_column('nid_doc')
        batch_op.drop_column('nid_number')
        batch_op.drop_column('trade_license_doc')
        batch_op.drop_column('trade_license_no')
        batch_op.drop_column('city')
        batch_op.drop_column('business_type')

    # ### end Alembic commands ###
