"""B-0 bilingual content columns (_bn pairs)

Revision ID: 0532afbd9b57
Revises: b9756d3ee9d2
Create Date: 2026-05-26 04:57:10.399266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0532afbd9b57'
down_revision = 'b9756d3ee9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_bn', sa.String(length=120), nullable=True))

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_bn', sa.String(length=200), nullable=True))

    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_bn', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('description_bn', sa.Text(), nullable=True))

    with op.batch_alter_table('homepage_banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline_bn', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('subheadline_bn', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('button_text_bn', sa.String(length=60), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_bn', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('body_bn', sa.String(length=500), nullable=True))

    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_bn', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('value_bn', sa.String(length=500), nullable=True))

    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_bn', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('subtitle_bn', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('section_bn', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('body_html_bn', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('toc_json_bn', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('faq_json_bn', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('related_json_bn', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.drop_column('related_json_bn')
        batch_op.drop_column('faq_json_bn')
        batch_op.drop_column('toc_json_bn')
        batch_op.drop_column('body_html_bn')
        batch_op.drop_column('section_bn')
        batch_op.drop_column('subtitle_bn')
        batch_op.drop_column('title_bn')

    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.drop_column('value_bn')
        batch_op.drop_column('label_bn')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('body_bn')
        batch_op.drop_column('title_bn')

    with op.batch_alter_table('homepage_banners', schema=None) as batch_op:
        batch_op.drop_column('button_text_bn')
        batch_op.drop_column('subheadline_bn')
        batch_op.drop_column('headline_bn')

    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.drop_column('description_bn')
        batch_op.drop_column('title_bn')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_column('description_bn')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('name_bn')

    # ### end Alembic commands ###
