"""phase 15 chunk c seller flash sales and store promo banner

Revision ID: 425d01445ca5
Revises: 676294bb677f
Create Date: 2026-05-24 00:08:37.923426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425d01445ca5'
down_revision = '676294bb677f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_flash_sales_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_foreign_key(None, 'vendor_profiles', ['vendor_id'], ['id'])

    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_banner_text', sa.String(length=240), nullable=True))
        batch_op.add_column(sa.Column('promo_banner_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('promo_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.drop_column('promo_until')
        batch_op.drop_column('promo_banner_image')
        batch_op.drop_column('promo_banner_text')

    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_flash_sales_vendor_id'))
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
