"""Phase 15 v3b vendor delivery and cancel stats

Revision ID: 5656b22c3f85
Revises: ddba0f3a50ba
Create Date: 2026-05-23 23:35:30.804181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5656b22c3f85'
down_revision = 'ddba0f3a50ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # New NOT NULL columns on a populated table need a server_default.
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_delivery_days', sa.Numeric(precision=5, scale=2),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('cancel_rate', sa.Numeric(precision=5, scale=4),
                                      nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.drop_column('cancel_rate')
        batch_op.drop_column('avg_delivery_days')

    # ### end Alembic commands ###
