"""phase 5: vendor wallets and payout requests

Revision ID: 5875245f430e
Revises: ab8246d115f7
Create Date: 2026-05-23 01:37:52.334689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5875245f430e'
down_revision = 'ab8246d115f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('account_detail', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_wallets')
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_requests_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_status'))

    op.drop_table('payout_requests')
    # ### end Alembic commands ###
