"""phase 15 D-8 smart helpers schema

Revision ID: 5d65a11a53a3
Revises: 9eb0ff10699a
Create Date: 2026-05-24 03:21:16.334159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d65a11a53a3'
down_revision = '9eb0ff10699a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_answer_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['qa_answers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'user_id', name='uq_answer_vote_answer_user')
    )
    with op.batch_alter_table('qa_answer_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_answer_votes_answer_id'), ['answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_answer_votes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_pros_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_cons_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_summary_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('qa_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'helpful_count', sa.Integer(), nullable=False, server_default='0',
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_answers', schema=None) as batch_op:
        batch_op.drop_column('helpful_count')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('ai_summary_at')
        batch_op.drop_column('ai_cons_json')
        batch_op.drop_column('ai_pros_json')

    with op.batch_alter_table('qa_answer_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_answer_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_qa_answer_votes_answer_id'))

    op.drop_table('qa_answer_votes')
    # ### end Alembic commands ###
