"""phase 15 D-5 bulk pricing tiers

Revision ID: 6054cea898e5
Revises: fb18266a14f3
Create Date: 2026-05-24 02:49:01.316799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6054cea898e5'
down_revision = 'fb18266a14f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'min_quantity', name='uq_price_tier_product_qty')
    )
    with op.batch_alter_table('product_price_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_price_tiers_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_price_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_price_tiers_product_id'))

    op.drop_table('product_price_tiers')
    # ### end Alembic commands ###
