"""phase 15 v3c product sponsored promotion

Revision ID: 676294bb677f
Revises: 5656b22c3f85
Create Date: 2026-05-23 23:43:15.006018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676294bb677f'
down_revision = '5656b22c3f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sponsored', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('sponsored_until', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_is_sponsored'), ['is_sponsored'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_sponsored'))
        batch_op.drop_column('sponsored_until')
        batch_op.drop_column('is_sponsored')

    # ### end Alembic commands ###
