"""Phase 10 search signals and ranking boost

Revision ID: 7f78be0b16d7
Revises: eb2233ba2a6a
Create Date: 2026-05-23 04:26:43.150720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f78be0b16d7'
down_revision = 'eb2233ba2a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=160), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_logs_term'), ['term'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_logs_user_id'), ['user_id'], unique=False)

    op.create_table('product_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_views_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_views_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_views_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking_boost', sa.Numeric(precision=4, scale=2),
                                      nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.drop_column('ranking_boost')

    with op.batch_alter_table('product_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_product_views_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_views_created_at'))

    op.drop_table('product_views')
    with op.batch_alter_table('search_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_logs_term'))
        batch_op.drop_index(batch_op.f('ix_search_logs_created_at'))

    op.drop_table('search_logs')
    # ### end Alembic commands ###
