"""Phase 8 sub-order tracking events

Revision ID: 96a7d7403938
Revises: d994c0dfeb2f
Create Date: 2026-05-23 02:59:08.886905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a7d7403938'
down_revision = 'd994c0dfeb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sub_order_id'], ['sub_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_order_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sub_order_events_sub_order_id'), ['sub_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_order_events_sub_order_id'))
        batch_op.drop_index(batch_op.f('ix_sub_order_events_created_at'))

    op.drop_table('sub_order_events')
    # ### end Alembic commands ###
