"""phase 15 D-7 chat presence and voice

Revision ID: 9eb0ff10699a
Revises: fa39ddfb6e2c
Create Date: 2026-05-24 03:12:17.318086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb0ff10699a'
down_revision = 'fa39ddfb6e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('audio_path')

    # ### end Alembic commands ###
