"""Phase 9 flash sales and reward points

Revision ID: b36aef5bba0e
Revises: 9309ba344f5c
Create Date: 2026-05-23 03:39:58.611739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36aef5bba0e'
down_revision = '9309ba344f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flash_sales_slug'), ['slug'], unique=True)

    op.create_table('reward_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('flash_sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flash_sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('flash_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_discount_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['flash_sale_id'], ['flash_sales.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flash_sale_id', 'product_id', name='uq_flash_sale_product')
    )
    with op.batch_alter_table('flash_sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flash_sale_items_flash_sale_id'), ['flash_sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flash_sale_items_product_id'), ['product_id'], unique=False)

    # server_default back-fills existing rows to zero.
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_redeemed', sa.Integer(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('points_discount', sa.Numeric(precision=12, scale=2),
                                      nullable=False, server_default='0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_points', sa.Integer(),
                                      nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reward_points')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('points_discount')
        batch_op.drop_column('points_redeemed')

    with op.batch_alter_table('flash_sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flash_sale_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_flash_sale_items_flash_sale_id'))

    op.drop_table('flash_sale_items')
    with op.batch_alter_table('reward_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_reward_ledger_created_at'))

    op.drop_table('reward_ledger')
    with op.batch_alter_table('flash_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flash_sales_slug'))

    op.drop_table('flash_sales')
    # ### end Alembic commands ###
