"""static_pages — admin-editable footer content

Revision ID: b9756d3ee9d2
Revises: 03e2fa43574f
Create Date: 2026-05-26 03:35:11.513395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9756d3ee9d2'
down_revision = '03e2fa43574f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=True),
    sa.Column('section', sa.String(length=80), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('toc_json', sa.Text(), nullable=True),
    sa.Column('faq_json', sa.Text(), nullable=True),
    sa.Column('related_json', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_pages_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_pages_slug'))

    op.drop_table('static_pages')
    # ### end Alembic commands ###
