"""phase 1: vendor payout fields (bkash, nagad)

Revision ID: d686f33560e7
Revises: 0500a8293dff
Create Date: 2026-05-22 14:57:56.054341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd686f33560e7'
down_revision = '0500a8293dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bkash_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nagad_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.drop_column('nagad_number')
        batch_op.drop_column('bkash_number')

    # ### end Alembic commands ###
