"""Phase 8 chat thread support topic

Revision ID: d994c0dfeb2f
Revises: 6bbccc848f72
Create Date: 2026-05-23 02:44:32.575587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd994c0dfeb2f'
down_revision = '6bbccc848f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
