"""Phase 15 homepage banners

Revision ID: ddba0f3a50ba
Revises: f8300012f5b9
Create Date: 2026-05-23 06:57:54.066701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddba0f3a50ba'
down_revision = 'f8300012f5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('subheadline', sa.String(length=300), nullable=True),
    sa.Column('button_text', sa.String(length=60), nullable=True),
    sa.Column('button_url', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homepage_banners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homepage_banners_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homepage_banners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homepage_banners_kind'))

    op.drop_table('homepage_banners')
    # ### end Alembic commands ###
