"""Phase 10 product image embeddings

Revision ID: f8300012f5b9
Revises: 7f78be0b16d7
Create Date: 2026-05-23 05:17:16.890535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8300012f5b9'
down_revision = '7f78be0b16d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_embeddings_product_id'), ['product_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_embeddings_product_id'))

    op.drop_table('product_embeddings')
    # ### end Alembic commands ###
