"""Phase 9 reviews and rating aggregates

Revision ID: f9351638cd2b
Revises: 96a7d7403938
Create Date: 2026-05-23 03:11:51.395901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9351638cd2b'
down_revision = '96a7d7403938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_review_user_product')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('review_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_images_review_id'), ['review_id'], unique=False)

    # New NOT NULL columns on populated tables need a server_default so the
    # existing rows back-fill to 0 (unrated).
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_avg', sa.Numeric(precision=3, scale=2),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(),
                                      nullable=False, server_default='0'))

    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_avg', sa.Numeric(precision=3, scale=2),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(),
                                      nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_avg')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_avg')

    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_images_review_id'))

    op.drop_table('review_images')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))

    op.drop_table('reviews')
    # ### end Alembic commands ###
