"""phase 15 D-6 stock notifications

Revision ID: fa39ddfb6e2c
Revises: 6054cea898e5
Create Date: 2026-05-24 03:00:57.813673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa39ddfb6e2c'
down_revision = '6054cea898e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'email', name='uq_stock_notif_product_email')
    )
    with op.batch_alter_table('stock_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_notifications_notified_at'), ['notified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_notifications_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_notifications_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_notifications_notified_at'))
        batch_op.drop_index(batch_op.f('ix_stock_notifications_created_at'))

    op.drop_table('stock_notifications')
    # ### end Alembic commands ###
