"""phase 15 D-0 policy violations

Revision ID: fa87d5f3241a
Revises: 425d01445ca5
Create Date: 2026-05-24 01:37:40.916900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa87d5f3241a'
down_revision = '425d01445ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('ref_kind', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_violations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_violations_surface'), ['surface'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_violations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_violations_user_id'))
        batch_op.drop_index(batch_op.f('ix_policy_violations_surface'))
        batch_op.drop_index(batch_op.f('ix_policy_violations_created_at'))

    op.drop_table('policy_violations')
    # ### end Alembic commands ###
