"""phase 15 D-2 product specs and qa

Revision ID: fb18266a14f3
Revises: fa87d5f3241a
Create Date: 2026-05-24 02:10:29.533582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb18266a14f3'
down_revision = 'fa87d5f3241a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_specs_product_id'), ['product_id'], unique=False)

    op.create_table('qa_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('asker_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_questions_asker_id'), ['asker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_questions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_questions_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_questions_product_id'), ['product_id'], unique=False)

    op.create_table('qa_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('responder_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('is_seller_answer', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['qa_questions.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_answers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_answers_responder_id'), ['responder_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_answers_responder_id'))
        batch_op.drop_index(batch_op.f('ix_qa_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_qa_answers_created_at'))

    op.drop_table('qa_answers')
    with op.batch_alter_table('qa_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_questions_product_id'))
        batch_op.drop_index(batch_op.f('ix_qa_questions_is_public'))
        batch_op.drop_index(batch_op.f('ix_qa_questions_created_at'))
        batch_op.drop_index(batch_op.f('ix_qa_questions_asker_id'))

    op.drop_table('qa_questions')
    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_specs_product_id'))

    op.drop_table('product_specs')
    # ### end Alembic commands ###
